- name: Ansible conditions
  hosts: local
  connection: local
  
  vars_prompt:
    - name: NUMBER
      prompt: Enter the NUMBER
      private: false

  tasks:
    - name: Checking if NUMBER is greater than 50
      ansible.builtin.debug:
        msg: "Given {{ NUMBER }} is greater than 50"
      when: NUMBER | int > 50

    - name: Check if NUMBER less than 50
      ansible.builtin.debug:
        msg: "Given {{ NUMBER }} is less than 50"
      when: NUMBER | int < 50
