- name: Ansible conditions
  hosts: local
  connection: local
  vars_prompt:
    - name: number
      prompt: Enter the number

  tasks:
    - name: Checking if number is greater than 50
      ansible.builtin.debug:
        msg: Given {{ number }} is greater than 50
      when: number > 50

    - name: Check if number less than 50
      ansible.builtin.debug:
        msg: Given {{ number }} is less than 50
      when: number < 50