- name: Loops playbook
  hosts: frontend
  become: yes
  tasks:
    - name: Install tools using Loops
      ansible.builtin.package:
        name: "{{ item }}"
        state: "installed"
      loop:
        - nginx
        - mysql
        - zip
    - name: Install and Uninstall using Loops
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - {name: 'nginx', state: 'present'}
        - {name: 'mysql', state: 'absent'}
        - { name: 'zip', state: 'absent'}