- name: Install nginx
  hosts: frontend
  become: yes
  tasks:
    - name: Install Nginx server
      ansible.builtin.package:
        name:
          - nginx
        state: latest
    - name: Start service Nginx, if not started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
